### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IceCruelStuff** [utting98/py-to-cpp-converter#4]
When I run the PytoCpp.py script, it gives me this error:

```
Beginning Parsing
Traceback (most recent call last):
  File "PytoCpp.py", line 1181, in <module>
    converted_data = main('Vector2.py','CallTest.py') #parse Test.py file, function call examples are listed in CallTest.py, if no function calls do not pass second argument
  File "PytoCpp.py", line 1052, in main
    arg_val = general_access_node(arg) #get the value of the argument
  File "PytoCpp.py", line 1036, in general_access_node
    raise TypeError('Parser not found for type: %s' % type(node))
TypeError: Parser not found for type: <class '_ast.Constant'>
```

**Comment by utting98** [comment]
Hmm that's strange, it's a type of node I've not yet seen and handled, if I was to take a guess are you declaring a global or constant somewhere in your code? If possible could I see the code you are trying to convert to figure out what part is raising the issue?

**Comment by IceCruelStuff** [comment]
This is my code
```
class Vector2:
    def __init__(self, x: float = 0, y: float = 0):
        self.x = x
        self.y = y
```

**Comment by JulianJB** [comment]
I'm facing the same error even while trying to run the script for the `Test.py` and `CallTest.py` example files. I'm using Python 3.8, are there any updates regarding this issue?

**Comment by stayprivate** [comment]
Must be related to:

changed in version 3.8: Class ast.Constant is now used for all constants."

Deprecated since version 3.8: Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.
